from enum import Enum


class Mode(str, Enum):
    BACKTEST = "backtest"
    PAPER = "paper"
    LIVE = "live"


class DecisionType(str, Enum):
    ENTER_LONG = "ENTER_LONG"
    ADD_LONG = "ADD_LONG"
    REDUCE_LONG = "REDUCE_LONG"
    EXIT_LONG = "EXIT_LONG"
    REJECTED = "REJECTED"


class DecisionStatus(str, Enum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    EXECUTED = "EXECUTED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class RegimeLabel(str, Enum):
    BULL_TRENDING = "BULL_TRENDING"
    BULL_RANGING = "BULL_RANGING"
    BEAR_RANGING = "BEAR_RANGING"
    BEAR_TRENDING = "BEAR_TRENDING"


class PeriodType(str, Enum):
    DAILY = "DAILY"
    QUARTERLY = "QUARTERLY"
    ANNUAL = "ANNUAL"
    STATIC = "STATIC"


class SignalState(str, Enum):
    ENTER = "ENTER"
    ENTER_PARTIAL = "ENTER_PARTIAL"
    ADD_PARTIAL = "ADD_PARTIAL"
    REDUCE_PARTIAL = "REDUCE_PARTIAL"
    EXIT_FULL = "EXIT_FULL"
    HOLD = "HOLD"
    EXIT = "EXIT"
    REJECT = "REJECT"


class SignalModuleName(str, Enum):
    TREND = "TREND"
    PULLBACK = "PULLBACK"
    MOMENTUM_QUALITY = "MOMENTUM_QUALITY"
    MEAN_REVERSION_VETO = "MEAN_REVERSION_VETO"
    FUNDAMENTAL_QUALITY = "FUNDAMENTAL_QUALITY"
    REGIME_GATE = "REGIME_GATE"
    LIQUIDITY_GATE = "LIQUIDITY_GATE"
    EVENT_RISK_GATE = "EVENT_RISK_GATE"


class StrategyVersion(str, Enum):
    V1_MASTER = "V1_MASTER"


class CandidateStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    REJECTED_NEGATIVE_EDGE = "REJECTED_NEGATIVE_EDGE"
    REJECTED_DRAWDOWN = "REJECTED_DRAWDOWN"
    REJECTED_DRAWDOWN_DURATION = "REJECTED_DRAWDOWN_DURATION"
    REJECTED_TURNOVER = "REJECTED_TURNOVER"
    REJECTED_HOLDING_PERIOD = "REJECTED_HOLDING_PERIOD"
    REJECTED_OOS_DECAY = "REJECTED_OOS_DECAY"
    REJECTED_TOO_FEW_TRADES = "REJECTED_TOO_FEW_TRADES"
    REJECTED_CONCENTRATION = "REJECTED_CONCENTRATION"
    REJECTED_HEAT_BREACH = "REJECTED_HEAT_BREACH"
    REJECTED_SEASONALITY_FRAGILE = "REJECTED_SEASONALITY_FRAGILE"
